[project]
name = "OTProf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pip>=26.1.2",
    "wrf_massive",
]

[tool.uv.sources]
wrf_massive = { path = "submodules/wrf-massive", editable = true }

[tool.ruff]
line-length = 120  # align with pycharm
